# Generated by Django 3.2.8 on 2021-10-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_comment_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=1),
        ),
    ]
