# Generated by Django 3.2.8 on 2021-10-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_comment_comment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_time',
        ),
    ]
